# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200308_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punejobs',
            name='jobnum',
        ),
    ]
